### ISSUE TITLE
mobile app

### ISSUE THREAD

**Issue by HknBskc** [javawizard/ha-navbar-position#1]
how to activate in mobile app (ios)

**Comment by javawizard** [comment]
Great question - it's only possible to activate this via URL parameters right now, so activating in the HA mobile app is more or less a no go.

Quickest workaround to implement is probably a custom lovelace card with a toggle to turn this on and off. Let me throw something together real quick...

**Comment by javawizard** [comment]
@HknBskc Give that a go - after updating, you should now be able to add a `Navbar Position Configuration Card` card to a dashboard and then tap the button in that card to move the navbar to the bottom. Let me know how it works for you!

**Comment by HknBskc** [comment]
> 
worked, thank you 😊

![13853E9D-1568-49B4-B4F0-229F615840C2](https://user-images.githubusercontent.com/1430728/167287717-80790bd8-8c4d-4f0d-923e-59cb9cab5f99.png)

**Comment by javawizard** [comment]
Excellent, you bet. Thanks for confirming!
