### ISSUE TITLE
navbar not moving to bottom after upgrading to core 2023.4.0

### ISSUE THREAD

**Issue by kaizersoje** [javawizard/ha-navbar-position#5]
navbar is now at the top after upgrading to core 2023.4.0. Even after adding `?navbar=bottom` to the end of the url, the navbar is still at the top.

**Comment by Greenphlem** [comment]
Yep, same issue on 2023.4.2

**Comment by Jawyman42** [comment]
Just stopping by to report the same. Ty

**Comment by Greenphlem** [comment]
I just made a PR to this repo with that fix since the user on that forum stated they didn't know how to do so. 

https://github.com/javawizard/ha-navbar-position/pull/7

**Comment by Jawyman42** [comment]
Thank you. I tried to make the change as well but couldn't quite figure it
out. I can if I spend enough time on it but would love to just see it
implemented before I do! Thanks again

**Comment by Greenphlem** [comment]
You can take a look at my repo and add it to your HACS custom repos, it will work. I'll look at updating it more with some of the requests here.

**Comment by smcue** [comment]
> You can take a look at my repo and add it to your HACS custom repos, it will work. I'll look at updating it more with some of the requests here.

Ah, great thanks! It seems be broken in the latest build (2023.5) even with your recent commit however.

**Comment by kmil4** [comment]
@Greenphlem is there a known fix? Still broken for me too. Sorry I would offer help but I'm not a dev, just an enthusiast. I really miss the bottom nav, doesn't seem to be any alternatives out there.

**Comment by javawizard** [comment]
This should be fixed now. Update via HACS and let me know if you still see the problem!
